# Generated by Django 5.2.4 on 2025-07-11 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todoapp',
            old_name='is_done',
            new_name='is_completed',
        ),
    ]
